version: '3.2'
volumes:
    grafana_data: {}

services:
  # simple myself setup
  mysql8:
    image: mysql:latest
    container_name: mysql8
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123

  # grafana used for graphing mysql data
  grafana:
    image: grafana/grafana
    container_name: grafana8
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
#       - ./entrypoint.sh:/app/entrypoint.sh
      - ./grafana/plugins:/var/lib/grafana/plugins
#       - grafana_data:/var/lib/grafana      
#    entrypoint:
#      - sh /app/entrypoint.sh


  # tool to connect to mysql instance, and allow prometheus to collect mysql stats
  mysql_exporter8:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter8
    links:
      - mysql8
    environment:
      DATA_SOURCE_NAME: root:123@(172.26.0.2:3306)/testdb
    ports:
      - '9104:9104'

    #command: /bin/mysql_exporter8 collect.binlog_size=true collect.info_schema.processlist=true
    #command: ["-web.listen-address=:9104", "-collect.global_status=true", "-collect.global_variables=false", "-collect.slave_status=false", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
    labels:
      - "mon.percona.container_type=collector"
    depends_on:
      - mysql8



  node-exporter8:
    image: prom/node-exporter
    container_name: node-exporter8
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.textfile.directory=/etc/node-exporter/"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'


  cadvisor8:
      image: google/cadvisor:latest
      container_name: cadvisor8
      ports:
        - '8082:8082'
      volumes:
        - '/:/rootfs'
        - '/var/run:/var/run'
        - '/sys:/host/sys'
        - '/var/lib/docker:/var/lib/docker'

  engine-proxy8:
    image: basi/socat
    container_name: engine-proxy8
    ports:
      - 4999:4999


#  mysqld_exporter_high_res:
#    image: prom/mysqld-exporter:latest
#    container_name: mysql_exporter_hres
#    environment:
#      DATA_SOURCE_NAME: prometheus:prometheus@(db1_mysql:3306)/
#    ports:
#      - "9104:9104"
#    command: ["-web.listen-address=:9104", "-collect.global_status=true", "-collect.global_variables=false", "-collect.slave_status=false", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]
#    labels:
#      - "mon.percona.container_type=collector"
#    depends_on:
#      - mysql8

  # prometheus stores and handles timeseries data for statistics around mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus8
    volumes:
      - ./prometheus:/etc/prometheus
    links:
      - mysql_exporter8
    ports:
      - 9090:9090
