global:
  scrape_interval:     15s # scrape targets every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # scrape targets every 15 seconds.: 5s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus-exporter
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mysql-exporter
    static_configs:
      - targets: ['localhost:9104']
        labels:
          alias: mysql-exporter


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor8:8080']

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter8:9100' ]

  - job_name: 'proxy'
    static_configs:
      - targets: [ 'engine-proxy8:4999' ]



    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s