global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: prometheus-exporter
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mysql-exporter
    static_configs:
      - targets: ['localhost:9104']
        labels:
          alias: mysql-exporter
