{
 "title": "DashboardMysql",
 "time": { "from": "2019-02-20T11:48:25.549Z", "to": "2019-03-24T11:48:25.549Z" },
 "panels": [
  {
   "title": "value1 over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueOne\nFROM metric_values\n-- WHERE\n  -- $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "sum over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(valueOne)  \nFROM metric_values\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "value2 over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueTwo\nFROM metric_values\n-- WHERE\n  -- $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueOne,\n  valueTwo\nFROM metric_values\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "content": "\n# Title\n\n## Contanairs:\n### from 0 to 5000\n### alert at 4000\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "alert list",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueOne\nFROM metric_values\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  time as 'Date',\n  valueOne as 'Temperature'\n FROM metric_values"
    }
   ]
  }
 ]
}