{
 "title": "DashboardMysql",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "value1 over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueOne\nFROM metric_values\n-- WHERE\n  -- $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "sum over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  sum(valueOne)  \nFROM metric_values\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "value2 over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  valueTwo\nFROM metric_values\n-- WHERE\n  -- $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time as 'Date',\n  valueOne as 'Temperature'\n FROM metric_values"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measurement,\n  sum(valueOne)  \nFROM metric_values\nGROUP BY measurement;"
    }
   ]
  }
 ]
}